[workspace]
members = ["tmplx", "tmplx-test"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Vincent SOYSOUVANH <vincent.soysouvanh@gmail.com>"]
description = "Tmplx is a Code-Gen-First HTML template engine for Rust, architecturally constrained to guarantee zero dynamic allocation (0 bytes of heap for static markup) at runtime."
readme = "README.md"
repository = "https://github.com/soysouvanh/tmplx"
license = "MIT"
keywords = ["template", "html", "zero-allocation", "build-time"]
categories = ["template-engine", "web-programming"]
