[package]
name = "tmplx-test"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Integration test suite for the Tmplx framework."
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
tmplx = { path = "../tmplx" }

[build-dependencies]
tmplx = { path = "../tmplx" }

[dev-dependencies]
criterion = "0.8.2"
askama = "0.16.0"
tera = "2.1.0"
lazy_static = "1.4"
sailfish = "0.11.2"
maud = "0.27.0"
markup = "0.16.0"
serde_json = "1.0.151"

[[bench]]
name = "compare_engines"
harness = false
