// src/tmplx_runtime.rs
//
// Module written once by hand and committed — NOT regenerated by build.rs
// (§5.4). Contains only write_escaped (§6), copied verbatim from
// the spec.
//
// SECURITY (§14 of the tmplx specification): `{%= %}` (RAW output,
// without passing through this function) is the shortest syntax of
// the tmplx grammar — escaping via `write_escaped`
// (`{%%= %}` in the mockup) must be requested EXPLICITLY. This is
// the opposite of the default convention of typical Rust template engines
// (Tera, Askama escape by default). Intentional choice,
// kept as is: any mockup binding a parameter of
// `render_extreme` to untrusted user input must use
// `{%%= %}`, otherwise it's a direct HTML/XSS injection in the output.

#[inline(always)]
pub fn write_escaped(output: &mut String, value: &str) {
    let mut last = 0;
    for (i, b) in value.bytes().enumerate() {
        let esc = match b {
            b'&' => "&amp;",
            b'<' => "&lt;",
            b'>' => "&gt;",
            b'"' => "&quot;",
            b'\'' => "&#39;",
            _ => continue,
        };
        output.push_str(&value[last..i]);
        output.push_str(esc);
        last = i + 1;
    }
    output.push_str(&value[last..]);
}

#[inline(always)]
pub fn write_escaped_js(output: &mut String, value: &str) {
    let mut last = 0;
    for (i, b) in value.bytes().enumerate() {
        let esc = match b {
            b'\\' => "\\\\",
            b'"' => "\\\"",
            b'\'' => "\\'",
            b'\n' => "\\n",
            b'\r' => "\\r",
            b'\t' => "\\t",
            b'<' => "\\x3C",
            b'>' => "\\x3E",
            _ => continue,
        };
        output.push_str(&value[last..i]);
        output.push_str(esc);
        last = i + 1;
    }
    output.push_str(&value[last..]);
}

#[inline(always)]
pub fn write_escaped_url(output: &mut String, value: &str) {
    const HEX_CHARS: &[u8; 16] = b"0123456789ABCDEF";
    let mut last = 0;
    let bytes = value.as_bytes();
    for i in 0..bytes.len() {
        let b = bytes[i];
        if matches!(b, b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~') {
            continue;
        }
        output.push_str(&value[last..i]);
        let mut enc = [b'%', 0, 0];
        enc[1] = HEX_CHARS[(b >> 4) as usize];
        enc[2] = HEX_CHARS[(b & 15) as usize];
        output.push_str(unsafe { std::str::from_utf8_unchecked(&enc) });
        last = i + 1;
    }
    output.push_str(&value[last..]);
}

#[cfg(test)]
mod tests {
    use super::*;

    // Entity table of §6, tested character by character.
    #[test]
    fn individual_entity_table() {
        let cases = [
            ("&", "&amp;"),
            ("<", "&lt;"),
            (">", "&gt;"),
            ("\"", "&quot;"),
            ("'", "&#39;"),
        ];
        for (input, expected) in cases {
            let mut out = String::new();
            write_escaped(&mut out, input);
            assert_eq!(out, expected);
        }
    }

    // Exact examples given in §6.
    #[test]
    fn spec_reference_examples() {
        let mut out = String::new();
        write_escaped(&mut out, "Paul \"the Great\"");
        assert_eq!(out, "Paul &quot;the Great&quot;");

        let mut out = String::new();
        write_escaped(&mut out, "O'Brien <script>");
        assert_eq!(out, "O&#39;Brien &lt;script&gt;");
    }

    // Regression test on the double-escaping risk described in §6,
    // reason 2: an '&' produced by escaping a neighboring character
    // must never be re-escaped. Here the input literally contains the
    // characters '&', 'a', 'm', 'p', ';' — the only special character is
    // the initial '&'.
    #[test]
    fn no_double_escaping() {
        let mut out = String::new();
        write_escaped(&mut out, "&amp;");
        assert_eq!(out, "&amp;amp;");
    }

    // Text without special character: copied without additional allocation
    // of content (no substitution should occur).
    #[test]
    fn text_without_special_character_unchanged() {
        let mut out = String::new();
        write_escaped(&mut out, "normal text 123");
        assert_eq!(out, "normal text 123");
    }

    // output is an accumulator buffer, not recreated: two successive calls
    // must concatenate, not overwrite (expected behavior from plan §5 —
    // write_escaped writes into the single output buffer).
    #[test]
    fn accumulation_in_the_same_buffer() {
        let mut out = String::new();
        write_escaped(&mut out, "a<b");
        write_escaped(&mut out, "&c");
        assert_eq!(out, "a&lt;b&amp;c");
    }
}
